// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCViA-OPmM3SevKLW_4UNkMTRQXyvOtiQ',
    appId: '1:353410083728:web:2e95b7ac61dc18b8622115',
    messagingSenderId: '353410083728',
    projectId: 'food-delivery-app-16423',
    authDomain: 'food-delivery-app-16423.firebaseapp.com',
    storageBucket: 'food-delivery-app-16423.appspot.com',
    measurementId: 'G-80PSKM9SG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0ZsDuhWSAw1VuthzwWLHlxlVQ5jejP0',
    appId: '1:353410083728:android:0170bae0aac79fa0622115',
    messagingSenderId: '353410083728',
    projectId: 'food-delivery-app-16423',
    storageBucket: 'food-delivery-app-16423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiELWzCvv9BCdIPa5m0BSAJxdtc2s928I',
    appId: '1:353410083728:ios:c0302fd472244f2e622115',
    messagingSenderId: '353410083728',
    projectId: 'food-delivery-app-16423',
    storageBucket: 'food-delivery-app-16423.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiELWzCvv9BCdIPa5m0BSAJxdtc2s928I',
    appId: '1:353410083728:ios:c0302fd472244f2e622115',
    messagingSenderId: '353410083728',
    projectId: 'food-delivery-app-16423',
    storageBucket: 'food-delivery-app-16423.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCViA-OPmM3SevKLW_4UNkMTRQXyvOtiQ',
    appId: '1:353410083728:web:f5a212a9e5ad6b01622115',
    messagingSenderId: '353410083728',
    projectId: 'food-delivery-app-16423',
    authDomain: 'food-delivery-app-16423.firebaseapp.com',
    storageBucket: 'food-delivery-app-16423.appspot.com',
    measurementId: 'G-PYVKZMTNW5',
  );
}
